version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  app:
    depends_on:
      - mongo
    build:
      context: .
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    command: yarn dev
volumes:
 mongodb:
 mongodb_config: