export const GAME_ALREADY_EXISTS = 'This game already exists.'
export const GENERIC_ERROR = 'There was an error with this operation.'
export const GAME_NOT_FOUND = 'This game does not exist.'
export const POINT_NOT_FOUND = 'This point does not exist.'
export const PLAYER_NOT_FOUND = 'This player does not exist.'
export const TEAM_NOT_FOUND = 'This team does not exist.'
